name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mhmmdfdlyas/dockerfile:k-ubuntu

    steps:
      - name: Build
        run: |
          git clone --depth=1 -b qcom_sm8250 \
            https://github.com/bengal-upstream/kernel_xiaomi_sm8250.git kernel

          export ARCH=arm64
          export SUBARCH=arm64

          clang --version

          cd kernel

          make O=out vendor/bengal-perf_defconfig

          make -j$(nproc --all) \
            O=out \
            LLVM=1 \
            LLVM_IAS=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          compression-level: 0
          if-no-files-found: warn
          path: kernel/out/arch/arm64/boot/**
