name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mhmmdfdlyas/dockerfile:k-ubuntu

    steps:
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/bengal-upstream/kernel_xiaomi_sm8250.git -b qcom_sm8250 kernel
          cd kernel

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ github.run_id }}

      - name: Clone AOSP Clang
        run: |
          git clone --depth=1 \
            https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64

          export CLANG_DIR=$(find clang -maxdepth 1 -type d -name 'clang-r*' | sort -V | tail -n1)
          export PATH=$PWD/$CLANG_DIR/bin:$PATH

          cd kernel

          make O=out vendor/bengal-perf_defconfig

          make -j$(nproc) \
            O=out \
            LLVM=1 \
            LLVM_IAS=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          compression-level: 0
          if-no-files-found: warn
          path: |
            kernel/out/arch/arm64/boot/**
